# Generated by Django 5.1.7 on 2025-06-16 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('posts', models.IntegerField()),
                ('bio_length', models.IntegerField()),
                ('profile_pic', models.IntegerField()),
                ('account_age_days', models.IntegerField()),
                ('engagement_ratio', models.FloatField()),
                ('result', models.CharField(max_length=10)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
