# Generated by Django 5.1.7 on 2025-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0002_alter_detectionhistory_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionhistory',
            name='username',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
